/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-11-25 14:31:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_002dus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Arumbu/Others/Learning/Learning_Workspace/JavaBuildCodeQuality/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourbank/WEB-INF/lib/struts2-core-2.3.8.jar!/META-INF/struts-tags.tld", Long.valueOf(1355717946000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.8.jar", Long.valueOf(1511446693018L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Our Bank || About Us</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"screen\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Modifications to Some Class-->\r\n");
      out.write("<!--Insert After Main CSS-->\r\n");
      out.write("<link href=\"css/basic.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.html", out, false);
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\" style=\"margin-top: 50px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"span1\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span10\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"well\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: red;\" >Our Profile</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"color: green;\">Genesis</strong><br> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div align=\"justify\"> Mr. S Vinayak Rai,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ta leading Non-Resident Indian businessman and head of the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tVinayak Group, conceived the vision of Our Bank -the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfirst of the new-generation private banks in India -and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tthrough collective contributions from the NRI community\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttowards India's economic and social development, brought our\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tBank into being.<br> <br> The Bank, formally\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tinaugurated in April 1994 by Dr. Manmohan Singh, Honourable\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tPrime Minister of India who was then the country’s Finance\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tMinister, started with a capital base of Rs.1,000 million\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t(USD 32 million at the prevailing exchange rate), of which\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tRs.600 million was raised through private placement from\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tIndian Residents while the balance Rs.400 million (USD 13\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmillion) was contributed by Non-Resident Indians.<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br> <br> <strong style=\"color: green;\">A New Era</strong><br> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Our Bank, which commenced its operations in 1994,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcaters to the needs of both consumer and corporate customers.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tIt has a robust technology platform supporting multi-channel\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdelivery capabilities. Our Bank has 441 branches, and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t796 ATMs spread across 303 geographic locations of the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcountry as on September 30, 2012.The Bank also has 2\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tRepresentative offices, one each in London and Dubai.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>The Bank believes in driving its business through\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttechnology. It has multi-lateral tie-ups with other banks\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tproviding access to their ATMs for its customers. It enjoys\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclearing bank status for both major stock exchanges - BSE and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tNSE - and three major commodity exchanges in the country -\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tMCX, NCDEX, and NMCE. It also offers DP facilities for stock\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tand commodity segments. The Bank has been bestowed with the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmandate of being a Settlement Banker for six tea auction\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcentres.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<strong style=\"color: green;\">RATINGS:</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>‘ICRA AA’ for Lower Tier II subordinate debt program\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tand ‘ICRA AA-‘ for Upper Tier II bond program by ICRA.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t‘CRISIL A1+’ for certificate of deposit program by CRISIL.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t‘CARE AA’ for Lower Tier II subordinate debt program by CARE.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t‘Fitch AA-‘ for Long Term Debt Instruments and ‘Fitch A1+’\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfor Short Term Debt Instruments by Fitch Ratings.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"span1\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.html", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"bootstrap/js/jquery.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
