/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-11-25 14:29:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class safe_002dbanking_002dtips_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Arumbu/Others/Learning/Learning_Workspace/JavaBuildCodeQuality/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ourbank/WEB-INF/lib/struts2-core-2.3.8.jar!/META-INF/struts-tags.tld", Long.valueOf(1355717946000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.3.8.jar", Long.valueOf(1511446693018L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Our Bank || Safe Banking Tips</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link href=\"bootstrap/css/bootstrap-responsive.css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"screen\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Modifications to Some Class-->\r\n");
      out.write("<!--Insert After Main CSS-->\r\n");
      out.write("<link href=\"css/basic.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.html", out, false);
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\" style=\"margin-top: 50px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"span1\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"span10\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"well\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"contentLeft\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1 style=\"color: red;\">Safe Banking Tips</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>&nbsp;</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCustomer awareness and education on Internet banking security\r\n");
      out.write("\t\t\t\t\t\t\t\t\twas a point of emphasis in the guidance published by the FFIEC\r\n");
      out.write("\t\t\t\t\t\t\t\t\ton June 28th of 2011 titled <em>Supplement to\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tAuthentication in an Internet Banking Environment</em>. Increasing\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcustomer awareness of effective techniques for mitigating the\r\n");
      out.write("\t\t\t\t\t\t\t\t\trisk of fraud should be a major part of your customer education\r\n");
      out.write("\t\t\t\t\t\t\t\t\tprogram.\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>When developing educational material for your online\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbanking customers, it’s important to keep in mind both the\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvarying amount of technical knowledge and the amount of time an\r\n");
      out.write("\t\t\t\t\t\t\t\t\taverage customer will dedicate to reviewing the information.\r\n");
      out.write("\t\t\t\t\t\t\t\t\tThe majority of your customers are unlikely to spend hours of\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttheir time reading through educational materials containing\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttechnically detailed descriptions of common attacks and\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttechniques to avoid them. Providing simple and\r\n");
      out.write("\t\t\t\t\t\t\t\t\teasy-to-understand security tips can be an effective\r\n");
      out.write("\t\t\t\t\t\t\t\t\talternative to detailed security information filled with\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformation security jargon.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>The following sections outline common security tips that\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcould be included in your bank’s online banking customer\r\n");
      out.write("\t\t\t\t\t\t\t\t\teducation material. The tips provided below are not exhaustive,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbut they should provide a good starting point.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: green;\">General PC Security</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Update your software frequently</strong> to\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tensure you have the latest security patches. This includes\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tyour computer’s operating system and other installed software\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t(e.g. Web Browsers, Adobe Flash Player, Adobe Reader, Java,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tMicrosoft Office, etc.).</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Automate software updates</strong>, to when\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tthe software supports it, to ensure updates are not\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\toverlooked.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Maintain active and up-to-date\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tantivirus protection</strong> provided by a reputable vendor. Schedule\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tregular scans of your computer in addition to real-time\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tscanning.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Update your software frequently</strong> to\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tensure you have the latest security patches. This includes\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tyour computer’s operating system and other installed software\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t(e.g. Web Browsers, Adobe Flash Player, Adobe Reader, Java,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tMicrosoft Office, etc.).</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>If you suspect your computer is\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tinfected with malware</strong>, discontinue using it for banking,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tshopping, or other activitiesinvolving sensitive information.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tUse security software and/or professional help to find and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tremove malware.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Use firewalls</strong> on your local network\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tto add another layer of protection for all the devices that\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconnect through the firewall (e.g. PCs, smartphones, and\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttablets).</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Require a password to gain access.</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tLog off or lock your computer when not in use.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Use a cable lock to physically secure\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tlaptops</strong> when these devices are stored in an untrusted\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlocation.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: green;\">General Online Security</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Never click on suspicious links</strong> in\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\temails, tweets, posts, or online advertising. Links can take\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tyou to a different website than their labels indicate. Typing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tan address in your browser instead of clicking a link in an\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\temail is a safer alternative.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Only give sensitive information to\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twebsites using encryption</strong> so your information is protected as\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tit travels across the Internet. Verify the web address begins\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twith “https://” (the “s” is for secure) rather than just\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t“http://.” Some browsers also display a closed padlock.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Do not trust sites with certificate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twarnings or errors.</strong> These messages could be caused by your\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconnection being intercepted or the web server misrepresenting\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tits identity.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Avoid using public computers or\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpublic wireless access points</strong> for online banking and other\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tactivities involving sensitive information when possible.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Always “sign out” or “log off”</strong> of\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpassword protected websites when finished to prevent\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tunauthorized access. Simply closing the browser window may not\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tactually end your session.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Be cautious of unsolicited phone\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcalls, emails, or texts</strong> directing you to a website or\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequesting sensitive information.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: green;\">Password Best Practices</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Create a unique password for all the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdifferent systems you use.</strong> If you don’t, then one breach\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tleaves all your accounts vulnerable.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Never share your password over the\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tphone, in texts, by email, or in person.</strong> If you are asked for\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tyour password, it’s probably a scam.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Use unpredictable passwords</strong> with a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcombination of lowercase letters, capital letters, numbers,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tand special characters.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>The longer the password, the tougher\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tit is to crack.</strong> Use a password with at least eight\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcharacters. Every additional character exponentially\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstrengthens a password.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Avoid using obvious passwords</strong> such\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tas:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>your name</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>your business name</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>family member names</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>your username</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>birthdates</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li>dictionary words</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><strong>Choose a password you can remember\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twithout writing it down. If you do choose to write it down,</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstore it in a secure location.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 style=\"color: green;\">Institution Specific Information</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>In addition to generic security tips, your bank should\r\n");
      out.write("\t\t\t\t\t\t\t\t\talso include tips specific to your bank’s online banking\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenvironment. Information concerning multi-factor authentication\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsolutions or other controls utilized by the bank would be\r\n");
      out.write("\t\t\t\t\t\t\t\t\tuseful to mention.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>Your bank will also need to include contact information\r\n");
      out.write("\t\t\t\t\t\t\t\t\tto be used by customers to notify the bank of suspicious\r\n");
      out.write("\t\t\t\t\t\t\t\t\taccount activity or information security-related events. Having\r\n");
      out.write("\t\t\t\t\t\t\t\t\tthis information easily accessible can speed up the process of\r\n");
      out.write("\t\t\t\t\t\t\t\t\tyour customers notifying the bank of fraud-related events. The\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFFIEC guidance also mentions outlining the circumstances and\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmethods with which the institution will contact a customer on\r\n");
      out.write("\t\t\t\t\t\t\t\t\tan unsolicited basis regarding their Internet banking account.\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"span1\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.html", out, false);
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"bootstrap/js/jquery.js\"></script>\r\n");
      out.write("\t<script src=\"bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
